name: Automated Tests

on:
  push:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run test cases on push

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run test 1
      run: |
        python3 find_lowest_number.py test_data/test01_input.txt test_data/test01_output.txt
        diff test_data/test01_output.txt test_data/test01_expected.txt

    - name: Run test 2
      run: |
        python3 find_lowest_number.py test_data/test02_input.txt test_data/test02_output.txt
        diff test_data/test02_output.txt test_data/test02_expected.txt

    - name: Run test 3
      run: |
        python3 find_lowest_number.py test_data/test03_input.txt test_data/test03_output.txt
        diff test_data/test03_output.txt test_data/test03_expected.txt
